# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    env:
      OS: ${{ matrix.config.name }}
    strategy:
      matrix:
        config:
          - { name: "win64", os: windows-latest }
          - { name: "win32", os: windows-latest }
          - { name: "linux", os: ubuntu-16.04 }
          - { name: "macos", os: macos-latest }

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Display the path
        shell: pwsh
        run: echo ${env:PATH}
        
      - name: Display the Matrix Info
        shell: pwsh
        run: |
          Write-Output "<+> Matrix info: "
          Write-Output "  <-> Name: ${{matrix.config.name}}"
          Write-Output "  <-> OS  : ${{matrix.config.os}}"
          
      - name: Setup MSBuild
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@v1.0.1
          
      - name: Test MSBuild
        if: runner.os == 'Windows'
        run: |
          msbuild -version
          
      - name: Test MSBuild
        if: runner.os != 'Windows'
        run: |
          make --version
